// <auto-generated />
using System;
using GsDotNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GsDotNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeedbackConsumo", b =>
                {
                    b.Property<int>("IdFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FEEDBACK");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFeedback"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("MensagemFeedback")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("MENSAGEM_FEEDBACK");

                    b.HasKey("IdFeedback");

                    b.HasIndex("IdUsuario");

                    b.ToTable("FEEDBACK_CONSUMO", (string)null);
                });

            modelBuilder.Entity("GsDotNet.Models.ConsumoEnergia", b =>
                {
                    b.Property<int>("IdConsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSUMO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsumo"));

                    b.Property<decimal>("ConsumoKwh")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("CONSUMO_KWH");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_REGISTRO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdConsumo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CONSUMO_ENERGIA", (string)null);
                });

            modelBuilder.Entity("GsDotNet.Models.UsuarioEnergia", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIO_ENERGIA", (string)null);
                });

            modelBuilder.Entity("HistoricoConsumo", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_HISTORICO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<decimal>("MediaMensal")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("MEDIA_MENSAL");

                    b.Property<decimal>("TotalConsumo")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("TOTAL_CONSUMO");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdUsuario");

                    b.ToTable("HISTORICO_CONSUMO", (string)null);
                });

            modelBuilder.Entity("FeedbackConsumo", b =>
                {
                    b.HasOne("GsDotNet.Models.UsuarioEnergia", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GsDotNet.Models.ConsumoEnergia", b =>
                {
                    b.HasOne("GsDotNet.Models.UsuarioEnergia", "Usuario")
                        .WithMany("Consumos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HistoricoConsumo", b =>
                {
                    b.HasOne("GsDotNet.Models.UsuarioEnergia", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GsDotNet.Models.UsuarioEnergia", b =>
                {
                    b.Navigation("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
